export const UZ_BOOKS_NAMES = [
  "Ibtido",
  "Chiqish",
  "Levilar",
  "Sahroda",
  "Qonunlar",
  "Yoshua",
  "Hakamlar",
  "Rut",
  "Shohlar (birinchi kitob)",
  "Shohlar (ikkinchi kitob)",
  "Shohlar (uchinchi kitob)",
  "Shohlar (to‘rtinchi kitob)",
  "Solnomalar (birinchi kitob)",
  "Solnomalar (ikkinchi kitob)",
  "Ezra",
  "Naximiyo",
  "Ester",
  "Ayub",
  "Zabur",
  "Sulaymonning hikmatlari",
  "Voiz",
  "Sulaymonning go‘zal qo‘shig‘i",
  "Ishayo",
  "Yeremiyo",
  "Yeremiyoning marsiyasi",
  "Hizqiyo",
  "Doniyor",
  "Xo‘sheya",
  "Yo‘el",
  "Amos",
  "Obodiyo",
  "Yunus",
  "Mixo",
  "Noxum",
  "Xabaqquq",
  "Zafaniyo",
  "Xaggey",
  "Zakariyo",
  "Malaki",
  "Matto Muqaddas xushxabar",
  "Mark Muqaddas xushxabar",
  "Luqo Muqaddas xushxabar",
  "Yuhanno Muqaddas xushxabar",
  "Havoriylarning faoliyati",
  "Yoqubning maktubi",
  "Butrusning birinchi maktubi",
  "Butrusning ikkinchi maktubi",
  "Yuhannoning birinchi maktubi",
  "Yuhannoning ikkinchi maktubi",
  "Yuhannoning uchinchi maktubi",
  "Yahudoning maktubi",
  "Rimliklarga maktub",
  "Korinfliklarga birinchi maktub",
  "Korinfliklarga ikkinchi maktub",
  "Galatiyaliklarga maktub",
  "Efesliklarga maktub",
  "Filippiliklarga maktub",
  "Kolosaliklarga maktub",
  "Salonikaliklarga birinchi maktub",
  "Salonikaliklarga ikkinchi maktub",
  "Timo‘tiyga birinchi maktub",
  "Timo‘tiyga ikkinchi maktub",
  "Titusga maktub",
  "Filimo‘nga maktub",
  "Ibroniylarga maktub",
  "Yuhannoga ko‘rsatilgan vahiy",
];
export const getBookIdBySlug = (slug: string) => {
  return UZ_BOOKS_NAMES.find((book) => book === slug);
};
