/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    books: Book;
    media: Media;
    bibles: Bible;
    'bible-books': BibleBook;
    'bible-chapters': BibleChapter;
    'bible-verses': BibleVerse;
    'content-reports': ContentReport;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    bibles: BiblesSelect<false> | BiblesSelect<true>;
    'bible-books': BibleBooksSelect<false> | BibleBooksSelect<true>;
    'bible-chapters': BibleChaptersSelect<false> | BibleChaptersSelect<true>;
    'bible-verses': BibleVersesSelect<false> | BibleVersesSelect<true>;
    'content-reports': ContentReportsSelect<false> | ContentReportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  title: string;
  /**
   * URL-friendly identifier used in book pages.
   */
  slug: string;
  locale: 'az' | 'ru';
  author?: string | null;
  subtitle?: string | null;
  description?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Used when the cover remains on the source website.
   */
  coverImageUrl?: string | null;
  source?: ('mukitob' | 'manual') | null;
  sourceBookKey?: string | null;
  /**
   * Numeric identifier from the source catalog.
   */
  sourceId?: number | null;
  detailUrl?: string | null;
  readUrl?: string | null;
  previewPages?: number | null;
  /**
   * Audio formats are intentionally excluded for now.
   */
  downloads?:
    | {
        format: string;
        label: string;
        fileSize?: string | null;
        description?: string | null;
        url: string;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bibles".
 */
export interface Bible {
  id: number;
  /**
   * Stable key used in public URLs, e.g. azb, barclay, mbc, muqaddas-kitob.
   */
  bibleKey: string;
  locale: 'az';
  primary: string;
  displayName?: string | null;
  secondary?: string[] | null;
  /**
   * The other bible shown alongside this one in split-screen view.
   */
  attachment?: (number | null) | Bible;
  defaultView: 'single-column' | 'split-screen';
  /**
   * CSS profile key used to style chapter HTML, e.g. azb, barclay.
   */
  formattingStyle?: string | null;
  /**
   * chapter = the Chapter HTML field is the source of truth. verse = Bible Verses are the source of truth and chapter HTML is derived, read-only, and kept only as a rollback artifact. Only corpora with verse markup (azb) can use verse mode; prose commentaries cannot.
   */
  storageMode: 'chapter' | 'verse';
  /**
   * The noun only, e.g. "fəsil" — chapter 1 reads "1-ci fəsil", chapter 3 "3-cü fəsil". The ordinal suffix is derived from the number and the locale, so do not include it here.
   */
  chapterSlug?: string | null;
  introductionName?: string | null;
  /**
   * Optional per-chapter override, indexed by chapter number (index 0 = the introduction). Chapters without an entry fall back to the computed "N-ci fəsil" form, so the list does not have to cover the whole book.
   */
  mappingChapterSlug?: string[] | null;
  isIndependent?: boolean | null;
  isCommentary?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bible-books".
 */
export interface BibleBook {
  id: number;
  locale: 'az';
  /**
   * Zero-padded canonical id, e.g. "01".."66".
   */
  bookId: string;
  name: string;
  /**
   * Falls back to the long name if left blank.
   */
  shortName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bible-chapters".
 */
export interface BibleChapter {
  id: number;
  bible: number | Bible;
  book: number | BibleBook;
  /**
   * Auto-filled from the linked book.
   */
  bookNumber: string;
  /**
   * "0" = introduction, then "1", "2", … (no padding).
   */
  chapterId: string;
  /**
   * Auto-filled from the linked book.
   */
  locale?: 'az' | null;
  /**
   * Optional human-friendly label shown in the admin list.
   */
  title?: string | null;
  storageMode?: string | null;
  /**
   * Raw chapter HTML. Verse spans and custom classes are stored verbatim.
   */
  html?: string | null;
  lastEditedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bible-verses".
 */
export interface BibleVerse {
  id: number;
  bible: number | Bible;
  chapter: number | BibleChapter;
  /**
   * Auto-filled from the linked chapter.
   */
  bookNumber: string;
  /**
   * Auto-filled from the linked chapter.
   */
  chapterNumber: string;
  /**
   * Auto-filled from the linked chapter.
   */
  locale?: 'az' | null;
  /**
   * 0 = chapter preamble (blocks before the first verse marker).
   */
  verseNumber: number;
  /**
   * Last verse covered by this record. Greater than the verse number only for the 30 azb markers that label a merged range (e.g. 16-17 under id V16); equal to it otherwise. The marker text shown in the chapter is derived from these two numbers, not stored.
   */
  verseEnd?: number | null;
  /**
   * bookNumber:chapterId:verseNumber
   */
  ref?: string | null;
  /**
   * The verse as plain running text — no markup, no line breaks. Edit it here: saving rebuilds the verse body from what you type. This is also what full-text search indexes. Empty for the 8 verses that carry a marker but no text in critical-text translations.
   */
  plainText?: string | null;
  /**
   * [{ cls, html }] — headings/references emitted before this verse.
   */
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * [{ cls, html, newBlock }] — one entry per block the verse occupies. Verses imported before the flat-text switch may still span several. newBlock:false on the first entry means the verse starts part-way through the previous block.
   */
  segments:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lastEditedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-reports".
 */
export interface ContentReport {
  id: number;
  type: 'report' | 'contact';
  status: 'new' | 'reviewed' | 'resolved';
  /**
   * Full URL of the page the selection was made on.
   */
  pageUrl: string;
  /**
   * Empty for contact-only submissions.
   */
  selectedText?: string | null;
  /**
   * What the reporter says is wrong with the selected text.
   */
  comment?: string | null;
  /**
   * Left voluntarily by the reporter so we can reach out.
   */
  contact?: string | null;
  /**
   * sha256(ip + salt) — used for rate limiting, not the raw IP.
   */
  ipHash?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'bibles';
        value: number | Bible;
      } | null)
    | ({
        relationTo: 'bible-books';
        value: number | BibleBook;
      } | null)
    | ({
        relationTo: 'bible-chapters';
        value: number | BibleChapter;
      } | null)
    | ({
        relationTo: 'bible-verses';
        value: number | BibleVerse;
      } | null)
    | ({
        relationTo: 'content-reports';
        value: number | ContentReport;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  locale?: T;
  author?: T;
  subtitle?: T;
  description?: T;
  coverImage?: T;
  coverImageUrl?: T;
  source?: T;
  sourceBookKey?: T;
  sourceId?: T;
  detailUrl?: T;
  readUrl?: T;
  previewPages?: T;
  downloads?:
    | T
    | {
        format?: T;
        label?: T;
        fileSize?: T;
        description?: T;
        url?: T;
        sortOrder?: T;
        id?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bibles_select".
 */
export interface BiblesSelect<T extends boolean = true> {
  bibleKey?: T;
  locale?: T;
  primary?: T;
  displayName?: T;
  secondary?: T;
  attachment?: T;
  defaultView?: T;
  formattingStyle?: T;
  storageMode?: T;
  chapterSlug?: T;
  introductionName?: T;
  mappingChapterSlug?: T;
  isIndependent?: T;
  isCommentary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bible-books_select".
 */
export interface BibleBooksSelect<T extends boolean = true> {
  locale?: T;
  bookId?: T;
  name?: T;
  shortName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bible-chapters_select".
 */
export interface BibleChaptersSelect<T extends boolean = true> {
  bible?: T;
  book?: T;
  bookNumber?: T;
  chapterId?: T;
  locale?: T;
  title?: T;
  storageMode?: T;
  html?: T;
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bible-verses_select".
 */
export interface BibleVersesSelect<T extends boolean = true> {
  bible?: T;
  chapter?: T;
  bookNumber?: T;
  chapterNumber?: T;
  locale?: T;
  verseNumber?: T;
  verseEnd?: T;
  ref?: T;
  plainText?: T;
  before?: T;
  segments?: T;
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-reports_select".
 */
export interface ContentReportsSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  pageUrl?: T;
  selectedText?: T;
  comment?: T;
  contact?: T;
  ipHash?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}