export const UZ_BOOKS_NAMES = [
  "Ibtido",
  "Chiqish",
  "Levilar",
  "Sahroda",
  "Qonunlar",
  "Yoshua",
  "Hakamlar",
  "Rut",
  "Shohlar (birinchi kitob)",
  "Shohlar (ikkinchi kitob)",
  "Shohlar (uchinchi kitob)",
  "Shohlar (to'rtinchi kitob)",
  "Solnomalar (birinchi kitob)",
  "Solnomalar (ikkinchi kitob)",
  "Ezra",
  "Naximiyo",
  "Ester",
  "Ayub",
  "Zabur",
  "Sulaymonning hikmatlari",
  "Voiz",
  "Sulaymonning go'zal qo'shig'i",
  "Ishayo",
  "Yeremiyo",
  "Yeremiyoning marsiyasi",
  "Hizqiyo",
  "Doniyor",
  "Xo'sheya",
  "Yo'el",
  "Amos",
  "Obodiyo",
  "Yunus",
  "Mixo",
  "Noxum",
  "Xabaqquq",
  "Zafaniyo",
  "Xaggey",
  "Zakariyo",
  "Malaki",
  "Matto Muqaddas xushxabar",
  "Mark Muqaddas xushxabar",
  "Luqo Muqaddas xushxabar",
  "Yuhanno Muqaddas xushxabar",
  "Havoriylarning faoliyati",
  "Yoqubning maktubi",
  "Butrusning birinchi maktubi",
  "Butrusning ikkinchi maktubi",
  "Yuhannoning birinchi maktubi",
  "Yuhannoning ikkinchi maktubi",
  "Yuhannoning uchinchi maktubi",
  "Yahudoning maktubi",
  "Rimliklarga maktub",
  "Korinfliklarga birinchi maktub",
  "Korinfliklarga ikkinchi maktub",
  "Galatiyaliklarga maktub",
  "Efesliklarga maktub",
  "Filippiliklarga maktub",
  "Kolosaliklarga maktub",
  "Salonikaliklarga birinchi maktub",
  "Salonikaliklarga ikkinchi maktub",
  "Timo'tiyga birinchi maktub",
  "Timo'tiyga ikkinchi maktub",
  "Titusga maktub",
  "Filimo'nga maktub",
  "Ibroniylarga maktub",
  "Yuhannoga ko'rsatilgan vahiy",
];

export const AZ_BOOKS_NAMES = [
  "Yaradiliş",
  "Çixiş",
  "Levililər",
  "Saylar",
  "Qanunun Təkrari",
  "Yeşua",
  "Hakimlər",
  "Rut",
  "Birinci Şamuel",
  "Ikinci Şamuel",
  "Birinci Padşahlar",
  "Ikinci Padşahlar",
  "Birinci Salnamələr",
  "Ikinci Salnamələr",
  "Ezra",
  "Nehemya",
  "Ester",
  "Əyyub",
  "Zəbur",
  "Süleymanin Məsəlləri",
  "Vaiz",
  "Nəğmələr Nəğməsi",
  "Yeşaya",
  "Yeremya",
  "Mərsiyələr",
  "Yezekel",
  "Daniel",
  "Huşə",
  "Yoel",
  "Amos",
  "Avdiya",
  "Yunus",
  "Mikeya",
  "Nahum",
  "Habaqquq",
  "Sefanya",
  "Haqqay",
  "Zəkəriyyə",
  "Malaki",
  "Mattanın müjdəsi",
  "Markın müjdəsi",
  "Lukanın müjdəsi",
  "Yəhyanın müjdəsi",
  "Həvarilərin İşləri",
  "Romalılara məktub",
  "Korinflilərə birinci məktub",
  "Korinflilərə ikinci məktub",
  "Qalatiyalılara məktub",
  "Efeslilərə məktub",
  "Filipililərə məktub",
  "Kolosselilərə məktub",
  "Saloniklilərə birinci məktub",
  "Saloniklilərə ikinci məktub",
  "Timoteyə birinci məktub",
  "Timoteyə ikinci məktub",
  "Titə məktub",
  "Filimona məktub",
  "İbranilərə məktub",
  "Yaqubun məktubu",
  "Peterin birinci məktubu",
  "Peterin ikinci məktubu",
  "Yəhyanın birinci məktubu",
  "Yəhyanın ikinci məktubu",
  "Yəhyanın üçüncü məktubu",
  "Yəhudanın məktubu",
  "Vəhy"
];

export const AZ_CHAPTERS_NAMES = [
  "Giriş",
  "1-ci fəsil",
  "2-ci fəsil",
  "3-cü fəsil",
  "4-cü fəsil",
  "5-ci fəsil",
  "6-cı fəsil",
  "7-ci fəsil",
  "8-ci fəsil",
  "9-cu fəsil",
  "10-cu fəsil",
  "11-ci fəsil",
  "12-ci fəsil",
  "13-cü fəsil",
  "14-cü fəsil",
  "15-ci fəsil",
  "16-cı fəsil",
  "17-ci fəsil",
  "18-ci fəsil",
  "19-cu fəsil",
  "20-ci fəsil",
  "21-ci fəsil",
  "22-ci fəsil",
  "23-cü fəsil",
  "24-cü fəsil",
  "25-ci fəsil",
  "26-cı fəsil",
  "27-ci fəsil",
  "28-ci fəsil"
];
