import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense>
      <html lang="en">
        <body className="flex flex-col justify-between min-h-screen">
          <main className="flex-1 shrink">
            <Suspense>{children}</Suspense>
          </main>
          <Footer />
        </body>
      </html>
    </Suspense>
  );
}
