name: Build and Deploy to FTP

on:
  push:
    branches:
      - main
      - az
  workflow_dispatch:

jobs:
  deploy-uz:
    name: Build & Deploy uz (static)
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.5.0"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Create .env file
        working-directory: ./apps/uz
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn workspace @mbc/uz build
        env:
          NODE_ENV: production

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./apps/uz/out/
          server-dir: /

  deploy-az:
    name: Build & Deploy az (server)
    if: github.ref_name == 'az'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.5.0"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Create .env file
        working-directory: ./apps/az
        run: echo "${{ secrets.ENV_FILE_AZ }}" > .env

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn workspace @mbc/az build
        env:
          NODE_ENV: production

      - name: Upload .next to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER_AZ }}
          username: ${{ secrets.FTP_USERNAME_AZ }}
          password: ${{ secrets.FTP_PASSWORD_AZ }}
          local-dir: ./apps/az/.next/
          server-dir: /.next/
